tasks:
  - init: >
            npm install &&
            npm run build
    command: npm run watch
  - init: >
            cd ../ &&
            git clone https://github.com/phaserjs/examples.git &&
            cd examples &&
            npm install && npm start
ports:
  - port: 8080
    onOpen: open-preview
